### ISSUE TITLE
是我没安装好还是你这边有问题

### ISSUE THREAD

**Issue by hechuanhua** [tangsj/webpack-multipage-demo#1]
![qq 20160618125512](https://cloud.githubusercontent.com/assets/8540940/16169088/1e667896-3554-11e6-9f99-e782c3ede1f9.png)
为什么执行 npm run dev 是出现一个这样的界面？

**Comment by tangsj** [comment]
dev  在这里面没有什么用， 用build. 看文件的打包， 之前就是为了测试这个的

**Comment by hechuanhua** [comment]
问一下HtmlWebpackPlugin 能include一些公用的头部底部吗？具体怎么写

**Comment by tangsj** [comment]
https://github.com/ampedandwired/html-webpack-plugin/tree/master/examples/custom-template
